//----------------------------------------------------------
// This function takes input param User's Firestore document pointer
// and retrieves the "saved" array (of bookmarks) 
// and dynamically displays them in the gallery
//----------------------------------------------------------
// if (firebase.auth().currentUser !== null) 
//         console.log("user id: " + firebase.auth().currentUser.uid);
// const currentUser = firebase.auth().currentUser.uid;

function getBookmarks(userId) {
  console.log(userId);
    db.collection("users").doc(userId).get()
        .then(userDoc => {
					  // Get the Array of bookmarks
          let bookmarks = userDoc.data().historyList;
						// Get pointer the new card template
          let newcardTemplate = document.getElementById("pastListTemplate");
						// Iterate through the ARRAY of bookmarked hikes (document ID's)
            let arr = Object.keys(bookmarks);
            arr.forEach((historyListID) => {
              db.collection("users").doc(historyListID).get().then(doc => {
                  // var docID = doc.id;  //this is the autogenerated ID of the document
                  // console.log(doc.data().listName);
                  //clone the new card
                let newcard = newcardTemplate.content.cloneNode(true);
                let title = historyListID;
                console.log(historyListID);
                  //update title and some pertinant information
                  newcard.querySelector('#list-title').innerHTML = title;
                  newcard.querySelector('#use').onclick = () => useList(historyListID); // add event listener to the addbutton
                  newcard.querySelector('#delete').onclick = () => deleteList(historyListID); // add event listener to the addbutton
                //Finally, attach this new card to the gallery
                  listCards.appendChild(newcard);
              })
          });
        })
}
getBookmarks("yXsEZFc7kTdbuu3cePxcLdG9CBH3");

function useList(historyListID) {
  firebase.auth().onAuthStateChanged((user) => {
    // Check if a user is signed in:
    if (user) {
      const currentUser = db.collection("users").doc(user.uid);
      currentUser
      let temp = db.collection("users").doc(user.uid).collection("historyList").doc(historyListID);
      console.log(temp);
    } else {
    }
  });
}
function deleteList(historyListID) {
    if (confirm("Press a button!")) {
      console.log(historyListID);
      db.collection("users").doc(historyListID).update({
        historyListID: firebase.firestore.FieldValue.delete(),
      }).then(() => {
        console.log("List successfully deleted!");
      }).catch((error) => {
        console.error("Error removing list: ", error);
      });
      txt = "You deleted " + historyListID;
    } else {
      txt = "You pressed Cancel!";
    }
}
